### ISSUE TITLE
How to make default nil appears in Parameter.load/3 result

### ISSUE THREAD

**Issue by smartepsh** [phcurado/parameter#70]
## Demo

```elixir
defmodule SomeSchema do
  use Parameter.Schema

  param do
    field :key, :string, default: nil
  end
end

Parameter.load(SomeSchema, %{})
Parameter.load(SomeSchema, %{}, ignore_nil: true)
Parameter.load(SomeSchema, %{}, ignore_nil: false)
```
## Current Behaviour

All 3 loads will returns `%{}`.

## Expect Behaviour

Returns `%{key: nil}` at least with `Parameter.load(SomeSchema, %{}, ignore_nil: false)`.

PS... I don't want to load parameter to struct first, then use `Map.from_struct/1` to convert to a map.

**Comment by phcurado** [comment]
Hi, this indeed should not be the expected behaviour. I checked and it seems since `nil` value is used by default when no default is passed, it's being ignored when loading. 
I did a quick fix on the main branch, would you mind checking if it's now working as expected?

Thank you

**Comment by smartepsh** [comment]
@phcurado I've tested it. 

- If there is a `default: nil` on `field/has_one/has_many` definition explicitly, it will loads as `%{"{key}": nil}` which is my expected.
- If without `default` setting, the field will be ignored.

If the original design is "not explicitly set default to nil, the field is considered not to exist", I can understand this point.

I have to say, this fix was  pretty quick! Thanks a lot !

**Comment by phcurado** [comment]
thanks for testing @smartepsh.
The default behaviour is as you described, if a field is not sent and there is no default value, the library assumes it shouldn't be parsed and ignores it. If the fields should be strictly shown on the schema, it's better to parse as structs which is more convenient for a strict structure.
I generated the new version with this fix, feel free to use it: https://hex.pm/packages/parameter/0.14.0
